[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "prefetch-src 'self'; default-src 'self'; font-src 'self'; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; script-src 'self' https://www.googletagmanager.com 'sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj' 'sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx'; img-src 'self'; connect-src https://www.google-analytics.com; form-action https://slim.us7.list-manage.com; frame-ancestors 'none'; frame-src 'self' https://www.youtube.com youtube.com www.youtube.com;"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Feature-Policy = "microphone 'none'; geolocation 'none'"
